# Generated by Django 5.1.7 on 2025-03-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material_price',
            new_name='material_cost',
        ),
    ]
