# Generated by Django 5.1.7 on 2025-03-19 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0002_rename_material_price_material_material_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialfinish',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpq_app.material'),
        ),
    ]
