# Generated by Django 5.1.7 on 2025-03-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0003_materialfinish_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialfinish',
            old_name='finish_price',
            new_name='finish_cost',
        ),
    ]
