# Generated by Django 5.1.7 on 2025-03-19 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0004_rename_finish_price_materialfinish_finish_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpq_app.supplier'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='scale_by_height',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='scale_by_length',
            field=models.BooleanField(default=False),
        ),
    ]
