# Generated by Django 5.1.7 on 2025-03-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0005_product_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_labor',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_margin',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
