# Generated by Django 5.0.3 on 2025-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0006_product_product_labor_product_product_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
