# Generated by Django 5.1.7 on 2025-03-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0007_rename_scale_by_length_productmaterial_scale_by_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='scale_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
