# Generated by Django 5.1.7 on 2025-04-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0008_alter_productmaterial_scale_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
