# Generated by Django 5.1.7 on 2025-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0009_alter_material_material_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_labor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_margin',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_labor',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_margin',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
