# Generated by Django 5.1.7 on 2025-04-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0010_remove_product_product_labor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='additional_materials',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='aluminum_finish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aluminum_finish', to='cpq_app.materialfinish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='excluded_materials',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='glass_finish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='glass_finish', to='cpq_app.materialfinish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_height',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_width',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
