# Generated by Django 5.1.7 on 2025-04-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0011_remove_quotationitem_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.CharField(default='sds', max_length=50),
            preserve_default=False,
        ),
    ]
