# Generated by Django 5.1.7 on 2025-04-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0012_quotation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='aluminum_finish',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='glass_finish',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
