# Generated by Django 5.1.7 on 2025-04-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0013_alter_quotationitem_aluminum_finish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_created',
            new_name='account_created',
        ),
        migrations.RemoveField(
            model_name='account',
            name='access_level',
        ),
        migrations.AddField(
            model_name='account',
            name='account_level',
            field=models.CharField(choices=[('regular', 'Regular'), ('superuser', 'Superuser')], default='regular', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
