# Generated by Django 5.1.7 on 2025-04-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0014_rename_date_created_account_account_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='customer',
            new_name='account_id',
        ),
    ]
