# Generated by Django 5.1.7 on 2025-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0016_alter_account_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaterial',
            name='scale_ratio_second',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
