# Generated by Django 5.1.7 on 2025-04-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0017_productmaterial_scale_ratio_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='item_label',
            field=models.CharField(default='label', max_length=50),
            preserve_default=False,
        ),
    ]
