# Generated by Django 5.1.7 on 2025-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0018_quotation_item_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='item_label',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_label',
            field=models.CharField(default='Label', max_length=50),
            preserve_default=False,
        ),
    ]
