# Generated by Django 5.1.7 on 2025-04-22 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0019_remove_quotation_item_label_quotationitem_item_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='quotation_status',
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
