# Generated by Django 5.1.7 on 2025-04-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0020_remove_quotation_quotation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='additional_materials',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('item_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpq_app.quotationitem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpq_app.material')),
            ],
        ),
    ]
