# Generated by Django 5.1.7 on 2025-04-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0021_alter_quotationitem_additional_materials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='additional_materials',
        ),
    ]
