# Generated by Django 5.1.7 on 2025-04-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq_app', '0022_remove_quotationitem_additional_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaterial',
            name='finish',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
